### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by Saiv46** [numerous-alpaca/auto-alpaca#1]
Looks like this project is not maintained anymore.

Solution: Update https://github.com/PrismarineJS/numerous-alpaca or use more generic 3rd-party solution (like Docker with CI/CD)

**Comment by rom1504** [comment]
No you're confused, this is not for flying-squid, this is for numerous
alpaca, the mcpe server

**Comment by Saiv46** [comment]
Maybe we shouldn't make `auto-[INSERT THING HERE]` repositories and instead let users decide how it should update?

**Comment by rom1504** [comment]
Yes user can decide to run it in any way they like, they're not forced to use this
